export const space = {
  spacingStackQuarck: '0.25rem',
  spacingStackNano: '0.5rem',
  spacingStackXxxs: '1rem',
  spacingStackXxs: '1.5rem',
  spacingStackXs: '2rem',
  spacingStackSm: '2.5rem',
  spacingStackMd: '3rem',
  spacingStackLg: '3.5rem',
  spacingStackXl: '4rem',
  spacingStackXxl: '5rem',
  spacingStackXxxl: '7.5rem',
  spacingStackHuge: '10rem',
  spacingStackGiant: '12.5rem',
  spacingInsetQuarck: '0.25rem',
  spacingInsetNano: '0.5rem',
  spacingInsetXs: '1rem',
  spacingInsetSm: '1.5rem',
  spacingInsetMd: '2rem',
  spacingInsetLg: '2.5rem',
  spacingSquishQuarck: '0.25rem 0.5rem',
  spacingSquishNano: '0.5rem 1rem',
  spacingSquishXs: '1rem 1.5rem',
  spacingSquishSm: '1rem 2rem',
  spacingInlineQuarck: '0.25rem',
  spacingInlineNano: '0.5rem',
  spacingInlineXxxs: '1rem',
  spacingInlineXxs: '1.5rem',
  spacingInlineXs: '2rem',
  spacingInlineSm: '2.5rem',
  spacingInlineMd: '3rem',
  spacingInlineLg: '4rem',
  spacingInlineXl: '5rem',
};
